version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    click: "8.1.3"
    colorama: "0.4.61"
    ghp-import: "2.1.0"
    Jinja2: "3.1.2"
    Markdown: "3.3.7"
    MarkupSafe: "2.1.3"
    mergedeep: "1.3.4"
    mkdocs: "1.4.3"
    packaging: "23.1"
    python-dateutil: "2.8.2"
    PyYAML: "6.0"
    pyyaml_env_tag: "0.1"
    six: "1.16.0"
    watchdog: "3.0.0"


mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

